### ISSUE TITLE
JS也要做混淆吧？

### ISSUE THREAD

**Issue by voidguy** [MrChens/codeObfuscated#1]

**Comment by MrChens** [comment]
从理论上来说确实需要对JSPatch.js做加密，但是没加密也过了审核所以就没做了。还有个考虑点就是这个工具就是拿来做code混淆的，如果专门为jspatch做混淆的话可能就不是很通用了吧！（我猜的）
当然如果可以的话你帮忙做一个这个部分的加密。不胜感激。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
