### ISSUE TITLE
工具使用

### ISSUE THREAD

**Issue by songyuanhang** [MrChens/codeObfuscated#2]
使用脚本  ，build 报错obfuscated.sh: No such file or directory。没找到报错的原因。

**Comment by MrChens** [comment]
请问有把obfuscated.sh拷贝到工程的根目录下吗？

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MrChens** [comment]
能把这个报错的详细信息贴出来吗？

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
