### ISSUE TITLE
codeObfuscation.h引用问题

### ISSUE THREAD

**Issue by johntaiii** [MrChens/codeObfuscated#3]
工程里引用codeObfuscation.h文件后，混淆前的那些类名不是照样会被扫描到吗？

**Comment by MrChens** [comment]
不会.你不行的话可以混淆完以后用classdump导出头文件就知道了.

**Comment by johntaiii** [comment]
明白了，我现在在pch中import后，编译报链接错误，请问有碰到过吗？
<img width="494" alt="yh_mall xcworkspace xcode today at 11 52 06 am" src="https://cloud.githubusercontent.com/assets/2558009/25769677/a54e80c8-3252-11e7-8b69-8eed0b206e3d.png">

**Comment by MrChens** [comment]
能看下这个log完整的嘛？还有看下那个.h文件的

**Comment by johntaiii** [comment]
`#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Sat May  6 11:07:20 CST 2017
#define startEngine GajtltepIqKnuxMG
#define evaluateScriptWithPath gahCESndAmRvdyCx
#define handleException IYxCMavYmvnOyLSt
#define handleMemoryWarning QjJVmPOgupYzFJAt
#define defineStruct baevxmnHAjzqyZzy
#define addExtensions siCurHwUdfTmFGag
#define formatOCToJS iXaabSYLsMzelHUb
#define formatJSToOC sxjVClEqQpRNURvh
#define formatPointerOCToJS unGfoQxIurLrjSkj
#define formatRetainedCFTypeOCToJS dmFzVvRjRIVQjMxx
#define formatPointerJSToOC GGZtdIKjACnvjQne
#define includedScriptPaths LFrzcMWSuYkmXzHR
#define getStructDataWidthDict hqpJjDwSiltvnGVD
#define boxAssignObj eDoUdIJSEaVuesxC
#define boxWeakObj uBufUxICNtQGtEcU
#define boxClass wSrmORpAekClBOuf
#define boxPointer uGcpoemqKrdySnDb
#define boxObj NMTEYqolLChSWPiE
#define sizeOfStructTypes CASysDBMszWpZyHO
#define getDictOfStruct VExGpKGrrnAZveDc
#define structDefine vsBRQssUmMmXVvEV
#define registeredStruct fcVcgCzpsEfXJgJD
#define overideMethods VVoisxmWpNDZoYtP
#define unboxPointer JfvxMIBycSpxZQSo
#define unboxClass XgYICefrOhxZvLqh
#define jp_methodSignatureForSelector POGnWijVlfZHpJUx
#define jp_fixMethodSignature POUINAuklTobFIxp
#define JPBoxing tBonQqGxluHwNoSs
#define JPBlock PpniPJqxeQAoFemv
#define JPBlockWrapper RaaRhEqDeIIDRLpS
#define JPCFunction KGTkHXXNhUMsooWi
#define JPMemory MmJZJaVXkdhZxDgX
#define JPStructPointer lLwJhsBxtQHOJeKy
#define JPCGBitmapContext YHmJeLQeeRvIjNQg
#define JPCGColor UAqXQxrEzIHDddMg
#define JPCGContext IoMByRvDKIxDpfLH
#define JPCGGeometry zXpOMyVpaXKdGVsE
#define JPCGImage pdDQbFEvgtJlRAly
#define JPCGPath bzcJMKOhRPoroWza
#define JPCGTransform EBkpzbEVbpIPDbJK
#define JPCoreGraphics rAExnhpFtfvdkoiP
#define JPUIGeometry rAVKeKbQGFtwnmyQ
#define JPUIGraphics pStGLDVwIezUCQQY
#define JPUIImage ndtlvLdfeJekwfIb
#define JPUIKit kHVOZDjlUyUXvJos
#define JPCleaner wxjNsKfIJXXWloIO
#define JPDispatch bdHZDxfilXsmcRQN
#define JPMethodSignature HliUdECPDSqkCVVi
#define JPLocker ejTHvpsVTPeBfHhI
#define JPNumber AZsxMppNdBaCeATM
#define JPKeyCommands gxhaDUhnyKSzWdvA
#define SGDirWatchdog PLKKaUVGMPlDEwcD
#define JPProtocol PvXBvuobdkHOBcKk
#define JPSpecialInit MoAMTagNUanqrsjB
#define JPEngine YHjbaezaWqPNBbVD
#define JPLoader ZLXFavczQJHucOiY
#define JPLoaderInclude oItBdYFqiDrPLfBO
#define JPLoaderTestInclude snyJOJWMBGoYZJst
#define JPExtension yCEVKYUYuOdFBQmQ
#define JPPlayground bjZcfuRIxDauBUBE
#define JPDevErrorView gevZzaATGXRQjMmO
#define JPDevMenu enzEmkIoNEXAREqJ
#define JPDevMenuItem iPBoxkYvORAbCoat
#define JPDevTipView XsNbQixvcUXgqpue
#define JPDevMenuDelegate aKVnfXdNXyPhnrNU
#endif
`

**Comment by johntaiii** [comment]
`#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Sat May  6 11:07:20 CST 2017
#define startEngine GajtltepIqKnuxMG
#define evaluateScriptWithPath gahCESndAmRvdyCx
#define handleException IYxCMavYmvnOyLSt
#define handleMemoryWarning QjJVmPOgupYzFJAt
#define defineStruct baevxmnHAjzqyZzy
#define addExtensions siCurHwUdfTmFGag
#define formatOCToJS iXaabSYLsMzelHUb
#define formatJSToOC sxjVClEqQpRNURvh
#define formatPointerOCToJS unGfoQxIurLrjSkj
#define formatRetainedCFTypeOCToJS dmFzVvRjRIVQjMxx
#define formatPointerJSToOC GGZtdIKjACnvjQne
#define includedScriptPaths LFrzcMWSuYkmXzHR
#define getStructDataWidthDict hqpJjDwSiltvnGVD
#define boxAssignObj eDoUdIJSEaVuesxC
#define boxWeakObj uBufUxICNtQGtEcU
#define boxClass wSrmORpAekClBOuf
#define boxPointer uGcpoemqKrdySnDb
#define boxObj NMTEYqolLChSWPiE
#define sizeOfStructTypes CASysDBMszWpZyHO
#define getDictOfStruct VExGpKGrrnAZveDc
#define structDefine vsBRQssUmMmXVvEV
#define registeredStruct fcVcgCzpsEfXJgJD
#define overideMethods VVoisxmWpNDZoYtP
#define unboxPointer JfvxMIBycSpxZQSo
#define unboxClass XgYICefrOhxZvLqh
#define jp_methodSignatureForSelector POGnWijVlfZHpJUx
#define jp_fixMethodSignature POUINAuklTobFIxp
#define JPBoxing tBonQqGxluHwNoSs
#define JPBlock PpniPJqxeQAoFemv
#define JPBlockWrapper RaaRhEqDeIIDRLpS
#define JPCFunction KGTkHXXNhUMsooWi
#define JPMemory MmJZJaVXkdhZxDgX
#define JPStructPointer lLwJhsBxtQHOJeKy
#define JPCGBitmapContext YHmJeLQeeRvIjNQg
#define JPCGColor UAqXQxrEzIHDddMg
#define JPCGContext IoMByRvDKIxDpfLH
#define JPCGGeometry zXpOMyVpaXKdGVsE
#define JPCGImage pdDQbFEvgtJlRAly
#define JPCGPath bzcJMKOhRPoroWza
#define JPCGTransform EBkpzbEVbpIPDbJK
#define JPCoreGraphics rAExnhpFtfvdkoiP
#define JPUIGeometry rAVKeKbQGFtwnmyQ
#define JPUIGraphics pStGLDVwIezUCQQY
#define JPUIImage ndtlvLdfeJekwfIb
#define JPUIKit kHVOZDjlUyUXvJos
#define JPCleaner wxjNsKfIJXXWloIO
#define JPDispatch bdHZDxfilXsmcRQN
#define JPMethodSignature HliUdECPDSqkCVVi
#define JPLocker ejTHvpsVTPeBfHhI
#define JPNumber AZsxMppNdBaCeATM
#define JPKeyCommands gxhaDUhnyKSzWdvA
#define SGDirWatchdog PLKKaUVGMPlDEwcD
#define JPProtocol PvXBvuobdkHOBcKk
#define JPSpecialInit MoAMTagNUanqrsjB
#define JPEngine YHjbaezaWqPNBbVD
#define JPLoader ZLXFavczQJHucOiY
#define JPLoaderInclude oItBdYFqiDrPLfBO
#define JPLoaderTestInclude snyJOJWMBGoYZJst
#define JPExtension yCEVKYUYuOdFBQmQ
#define JPPlayground bjZcfuRIxDauBUBE
#define JPDevErrorView gevZzaATGXRQjMmO
#define JPDevMenu enzEmkIoNEXAREqJ
#define JPDevMenuItem iPBoxkYvORAbCoat
#define JPDevTipView XsNbQixvcUXgqpue
#define JPDevMenuDelegate aKVnfXdNXyPhnrNU
#endif
`

**Comment by johntaiii** [comment]
<img width="439" alt="yh_mall xcworkspace xcode today at 12 09 48 pm" src="https://cloud.githubusercontent.com/assets/2558009/25769891/221a6fae-3258-11e7-8ec2-354ebed44ff3.png">
<img width="450" alt="today at 12 30 19 pm" src="https://cloud.githubusercontent.com/assets/2558009/25769892/227b44a0-3258-11e7-84c3-1e7074b02a21.png">

**Comment by MrChens** [comment]
你这是用cocoapod弄的jspatch吗？如果是的话我可能得回去研究下cocoapod怎么使用

**Comment by johntaiii** [comment]
是的...

**Comment by MrChens** [comment]
@johntaiii 你好。我今天试了下没发现你说的这个问题。。。
可能是我使用cocoapods的方式不一样。我上传一个[demo](https://github.com/MrChens/demo)，你看下。(我这种样子使用cocoapods的方式是蛮丑陋的。)
<img width="701" alt="3a3e4917-547b-4ae4-aafa-cd561a4ebab8" src="https://cloud.githubusercontent.com/assets/9456917/25779307/a54af660-3347-11e7-8f7f-eea6cc0fd8e2.png">
<img width="576" alt="bcf1d2c4-c277-4853-a03d-1e5b35452a82" src="https://cloud.githubusercontent.com/assets/9456917/25779323/f5355256-3347-11e7-945d-6f8c3ecfe13b.png">

**Comment by johntaiii** [comment]
你好，我后来改用直接引用jspatch的方式解决了这个问题，混淆确实起作用了，悲剧的是还是被苹果拒绝了。

**Comment by MrChens** [comment]
难道是jspatch.js文件也被检查了？

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johntaiii** [comment]
maybe..
