### ISSUE TITLE
请问现在还能用这个工具混淆jspatch过审吗？

### ISSUE THREAD

**Issue by xilin** [MrChens/codeObfuscated#4]
谢谢。

**Comment by MrChens** [comment]
不行.要用的话还得把JSPatch.js的文件混淆才行.
现在Apple对dlopen和dlsym的调用都查的很严.还是有些风险的，可以试试看jspatch平台上的最新版本看看.记得他们是吧JSPatch.js文件都混淆了的

发自我的 iPhone

**Comment by xilin** [comment]
好的，谢谢！

**Comment by MrChens** [comment]
@xilin 
我以前有存jspatch 1.7.2版本的sdk，你要的话我可以给你。

**Comment by xilin** [comment]
太好了，我的邮箱是linxi60@gmail.com
非常感谢！

**Comment by yibyli** [comment]
@MrChens 你好,我们现在正在做JSPatch的混淆,能给我也发一份1.7.2版本的sdk吗

**Comment by MrChens** [comment]
> @MrChens 你好,我们现在正在做JSPatch的混淆,能给我也发一份1.7.2版本的sdk吗

可以，我回去找一下看看。

**Comment by MrChens** [comment]
> @MrChens 你好,我们现在正在做JSPatch的混淆,能给我也发一份1.7.2版本的sdk吗

@yibyli 可以，我回去找一下看看。

**Comment by MrChens** [comment]
> @MrChens 你好,我们现在正在做JSPatch的混淆,能给我也发一份1.7.2版本的sdk吗

@yibyli 找到了，怎么给你？

**Comment by yibyli** [comment]
@MrChens 请您发到这个邮箱: yibyli@foxmail.com,多谢!

**Comment by LitDragon** [comment]
您好，我也需要一份JSPatch 1.7.2的版本，可以发给我吗，谢谢
邮箱：873098673@qq.com

**Comment by MrChens** [comment]
> 您好，我也需要一份JSPatch 1.7.2的版本，可以发给我吗，谢谢
> 邮箱：[873098673@qq.com](mailto:873098673@qq.com)
已经删除了，你问一下其他人看看

**Comment by MrChens** [comment]
> 您好，我也需要一份JSPatch 1.7.2的版本，可以发给我吗，谢谢
> 邮箱：[873098673@qq.com](mailto:873098673@qq.com)

@LitDragon 不好意思，已经删除很久了，你问一下其他人看看

**Comment by LitDragon** [comment]
> > 您好，我也需要一份JSPatch 1.7.2的版本，可以发给我吗，谢谢
> > 邮箱：[873098673@qq.com](mailto:873098673@qq.com)
> 
> @LitDragon 不好意思，已经删除很久了，你问一下其他人看看

没事，谢谢回复
